package com.example.gamewiki;

import android.os.Bundle;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {
    private RecyclerView recyclerView;
    private GameAdapter adapter;
    private ArrayList<Game> games;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));

        games = new ArrayList<>();
        games.add(new Game("Minecraft", R.drawable.logo_1, "Minecraft adalah game sandbox yang memungkinkan pemain membangun, menjelajah, dan bertahan hidup di dunia yang dihasilkan secara prosedural menggunakan blok. Dengan mode kreatif dan bertahan hidup, pemain bisa membangun struktur, melawan monster, dan berkreasi tanpa batas.", R.drawable.image_1, "Minecraft\n \nMinecraft adalah sebuah permainan bak pasir yang dikembangkan oleh pengembang permainan Swedia Mojang Studios. Permainan ini dibuat oleh Markus \"Notch\" Persson dalam bahasa pemrograman Java. Setelah beberapa versi pengujian pribadi awal, permainan ini pertama kali diterbitkan pada Mei 2009 sebelum sepenuhnya dirilis pada November 2011, kemudian Jens \"Jeb\" Bergensten mengambil alih pengembangan. Permainan ini adalah salah satu yang terlaris sepanjang masa, terjual lebih dari 238 juta kali dan dengan lebih dari 140 juta pemain aktif bulanan.\n" +
                "\n" +
                "Di Minecraft, pemain menjelajahi dunia 3D kotak-kotak dengan bioma Minecraft beragam yang dihasilkan secara prosedural, dan dapat menemukan dan membuat dari bahan baku, alat kerajinan, membangun struktur atau pekerjaan tanah, tergantung pada mode permainan, dapat melawan musuh yang dikendalikan oleh komputer, dan juga bekerja sama atau bersaing dengan pemain lain di dunia yang sama. Mode permainan dalam Minecraft termasuk mode bertahan hidup, di mana pemain harus mendapatkan sumber daya untuk membangun dunia dan menjaga kesehatan, dan mode kreatif, di mana pemain memiliki sumber daya tanpa batas. Pemain dapat memodifikasi game dengan mod untuk membuat mekanisme, item, tekstur, add-ons, dan aset alur permainan baru.\n" +
                "\n" +
                "Versi-versi awal permainan ini mendapat tanggapan secara positif, memenangkan beberapa penghargaan dan disebut sebagai salah satu permainan video terbaik yang pernah ada. Sosial media, parodi, adaptasi, barang dagangan, dan Minecon yang diselenggarakan tiap tahun memiliki peran besar dalam kepopuleran permainan ini. Minecraft juga digunakan dalam lingkungan edukasi untuk mengajarkan kimia, CAD, dan ilmu komputer. Pada tahun 2014, Mojang dan properti intelektual Minecraft dibeli Microsoft seharga US$2,5 miliar. Sejumlah game spin-off juga telah dikembangkan, seperti Minecraft: Story Mode, Minecraft Earth, Minecraft Dungeons, dan Minecraft Legends."));

        games.add(new Game("Valorant", R.drawable.logo_2, "Valorant adalah game first-person shooter (FPS) berbasis tim yang dikembangkan oleh Riot Games. Menggabungkan elemen taktis dengan kemampuan unik dari berbagai agen, game ini menghadirkan pertarungan strategis yang kompetitif.", R.drawable.image_2, "Valorant \n \n Valorant adalah penembak taktis berbasis tim dan penembak orang pertama yang diatur dalam dekat masa depan. Pemain bermain sebagai salah satu dari sekumpulan agen, karakter yang dirancang berdasarkan beberapa negara dan budaya di seluruh dunia. Dalam mode permainan utama, pemain ditugaskan ke tim menyerang atau bertahan dengan masing-masing tim memiliki lima pemain di dalamnya. Agen memiliki kemampuan unik, masing-masing membutuhkan biaya, serta kemampuan akhir unik yang membutuhkan pengisian melalui pembunuhan, kematian, atau aksi spike. Setiap pemain memulai setiap putaran dengan pistol \"classic\" dan satu atau lebih muatan \"kemampuan khas\". Senjata dan biaya kemampuan lainnya dapat dibeli menggunakan sistem ekonomi dalam permainan yang memberikan uang berdasarkan hasil putaran sebelumnya, pembunuhan apa pun yang menjadi tanggung jawab pemain, dan tindakan apa pun yang diambil dengan spike. Agen yang berbeda memungkinkan pemain menemukan lebih banyak cara untuk memasang Spike dan gaya pada musuh dengan scrappers, ahli strategi, dan pemburu dari setiap deskripsi. Saat ini, menawarkan 21 agen untuk dipilih. Mereka adalah Brimstone, Phoenix, Sage, Harbor, Sova, Gekko, Viper, Cypher, Reyna, Killjoy, Fade, Neon, Breach, Omen, Jett, Raze, Skye, Yoru, Astra, KAY/O, dan Chamber."));

        games.add(new Game("CS:GO", R.drawable.logo_3, "CS:GO adalah game FPS kompetitif yang mengadu dua tim, Terrorists dan Counter-Terrorists, dalam berbagai mode permainan berbasis objektif. Gameplay yang cepat dan strategi tim menjadi kunci kemenangan.", R.drawable.image_3, "CS:GO \n \n Counter Strike: Global Offensive (disingkat CSGO) adalah sebuah permainan dengan mode FPS yang dikembangkan oleh Valve Corporation dan Hidden Path Entertainment. Kedua perusahaan ini juga merupakan perusahaan yang mengembangkan Counter Strike: Source. Counter Strike: GO merupakan permainan keempat di dalam waralaba Counter Strike, tidak termasuk Counter Strike Neo dan Online. Counter Strike Global Offensive dirilis pada tanggal 21 Agustus, 2012 dan dapat dimainkan pada Microsoft Windows, OS X, Xbox Live Arcade dan Playstation Network versi Amerika. Counter Strike: Global Offensive menampilkan fitur-fitur klasiknya berupa peta yang ada dalam versi sebelumnya dan beberapa peta baru serta karakter tambahan. Permainan ini dapat dimainkan dengan menggunakan beberapa platform yang berbeda yaitu Windows, OS X dan PSN."));

        games.add(new Game("GTA V", R.drawable.logo4, "Game open-world dari Rockstar Games yang mengisahkan tiga karakter dalam dunia kejahatan di Los Santos. Menawarkan mode cerita yang mendalam serta GTA Online, di mana pemain bisa menjalankan misi, balapan, dan berbagai aktivitas lainnya.", R.drawable.image_4, "GTA V \n \n Grand Theft Auto V (sering disingkat sebagai GTA: V atau GTA: 5) adalah permainan laga-petualangan 2013 yang dikembangkan oleh Rockstar North dan diterbitkan oleh Rockstar Games. Ini adalah entri utama pertama dalam seri Grand Theft Auto sejak 2008 Grand Theft Auto IV. Berlatar di dalam negara bagian fiksi San Andreas, yang berbasis di California Selatan, kisah pemain tunggal mengikuti tiga kriminal dan upaya mereka untuk melakukan perampokan di bawah tekanan lembaga pemerintah yang korup serta penjahat yang berkuasa. Desain dunia terbuka memungkinkan pemain bebas berkeliaran di pedesaan terbuka San Andreas dan kota fiksi Los Santos, yang berbasis di Los Angeles, Amerika Serikat.\n" +
                "\n" +
                "Permainan ini dimainkan dari sudut pandang orang ketiga atau orang pertama, dan dunianya dinavigasi dengan berjalan kaki atau dengan kendaraan. Pemain mengontrol tiga protagonis utama di seluruh pemain tunggal dan beralih di antara mereka, baik selama dan di luar misi. Kisah ini berpusat pada urutan perampokan, dan banyak misi melibatkan penembakan dan mengemudi gameplay. Sistem \"buronan\" (wanted system) mengatur agresi tanggapan penegakan hukum terhadap pemain yang melakukan kejahatan. Grand Theft Auto Online, mode multipemain online permainan ini, memungkinkan hingga 30 pemain dapat bermain dalam berbagai mode kooperatif dan kompetitif yang berbeda.\n" +
                "\n" +
                "Pengembangan game ini dimulai sekitar waktu perilisan Grand Theft Auto IV dan dikerjakan secara bersama-sama oleh sejumlah studio Rockstar di seluruh dunia. Tim pengembang mengambil pengaruh dari banyak proyek mereka sebelumnya seperti Red Dead Redemption maupun Max Payne 3 dan mendesain game di antara tiga protagonis utama untuk berinovasi pada struktur inti pendahulunya. Sebagian besar pengembangannya merupakan kreasi dunia terbuka, dan beberapa anggota tim melakukan penelitian lapangan di sekitar California untuk mengambil rekaman bagi tim desain. Soundtrack game ini menampilkan skor orisinal yang disusun oleh tim produser yang berkolaborasi selama beberapa tahun. Grand Theft Auto V dirilis pada bulan September 2013 untuk PlayStation 3 dan Xbox 360, pada bulan November 2014 untuk PlayStation 4 dan Xbox One, pada bulan April 2015 untuk Windows, dan pada bulan Maret 2022 untuk PlayStation 5 dan Xbox Series X/S.[2]\n" +
                "\n" +
                "Dipasarkan secara luas dan diantisipasi secara luas, permainan memecahkan rekor penjualan industri dan menjadi produk hiburan dengan penjualan tercepat dalam sejarah, menghasilkan $800 juta di hari pertama dan $1 miliar dalam tiga hari pertama. Permainan ini menerima pujian kritis luas, dengan pujian yang diarahkan pada desain protagonis yang beragam, dunia terbuka, presentasi dan gameplay. Namun, hal itu menimbulkan kontroversi terkait dengan penggambaran kekerasan dan perempuan. Game ini memenangkan penghargaan akhir tahun termasuk penghargaan Game of the Year dari beberapa publikasi game, dan dianggap sebagai salah satu game konsol generasi ketujuh dan kedelapan yang paling penting dan termasuk di antara permainan video terbaik yang pernah dibuat. Permainan ini merupakan permainan video terlaris kedua sepanjang masa dengan lebih dari 175 juta kopi yang telah dikirimkan, dan pada bulan April 2018, menjadikan salah satu produk hiburan paling sukses secara finansial sepanjang masa, dengan pendapatan sekitar $6 miliar di seluruh dunia. Penggantinya sedang dalam pengembangan."));

        games.add(new Game("PUBG", R.drawable.logo_5, "Game battle royale yang mempertemukan 100 pemain dalam pertempuran bertahan hidup di berbagai peta. Dengan gameplay realistis, looting, dan strategi, pemain harus menjadi yang terakhir bertahan untuk memenangkan \"Winner Winner Chicken Dinner.", R.drawable.image_5, "PUBG \n \n PlayerUnknown’s Battlegrounds (PUBG) adalah game battle royale yang dikembangkan oleh PUBG Corporation, bagian dari Krafton. Game ini pertama kali dirilis dalam akses awal pada Maret 2017 dan resmi diluncurkan pada Desember 2017 untuk PC dan Xbox, diikuti oleh versi PlayStation dan PUBG Mobile pada tahun 2018. Sebagai salah satu pelopor genre battle royale, PUBG menghadirkan pengalaman bertahan hidup yang realistis, di mana 100 pemain bertarung dalam satu pertandingan hingga hanya tersisa satu pemenang yang mendapatkan kemenangan dengan pesan ikonik \"Winner Winner Chicken Dinner.\"\n" +
                "\n" +
                "Gameplay PUBG dimulai dengan pemain terjun dari pesawat dan memilih lokasi pendaratan di peta yang luas. Setelah mendarat, pemain harus segera mencari senjata, armor, dan perlengkapan medis untuk bertahan hidup. Selama permainan, area aman akan terus mengecil, memaksa pemain untuk berpindah ke zona yang lebih kecil sambil bertarung dengan musuh. Jika pemain tetap berada di luar zona aman terlalu lama, mereka akan kehilangan kesehatan secara bertahap hingga akhirnya tersingkir. Selain itu, ada juga zona merah, area yang secara acak dibombardir oleh serangan udara, memaksa pemain untuk mencari perlindungan. Strategi bertahan hidup dan keterampilan menembak sangat penting dalam permainan ini, terutama di fase akhir ketika hanya tersisa beberapa pemain di zona kecil yang penuh tekanan.\n" +
                "\n" +
                "PUBG menawarkan berbagai peta dengan karakteristik unik. Erangel adalah peta pertama dengan lanskap khas Eropa Timur yang penuh hutan dan bangunan, Miramar menghadirkan medan gurun luas dengan pertempuran jarak jauh, Sanhok memiliki lingkungan hutan tropis yang lebih kecil dengan tempo permainan cepat, Vikendi membawa suasana bersalju dengan area perkotaan yang kompleks, sementara Karakin adalah peta kecil dengan fitur dinding yang bisa dihancurkan. Setiap peta memberikan pengalaman yang berbeda, memaksa pemain untuk menyesuaikan strategi permainan mereka.\n" +
                "\n" +
                "Selain peta yang bervariasi, PUBG juga memiliki sistem senjata yang realistis, mulai dari senapan serbu (M416, AKM, SCAR-L), sniper rifle (AWM, Kar98k, M24), hingga pistol dan shotgun. Setiap senjata memiliki karakteristik tersendiri, seperti tingkat recoil, damage, dan kecepatan tembakan. Pemain juga dapat menggunakan granat, bom asap, dan Molotov untuk strategi pertempuran yang lebih dinamis. PUBG memberikan elemen tambahan berupa kendaraan seperti mobil, motor, dan perahu untuk membantu mobilitas pemain dalam menjelajahi peta yang luas.\n" +
                "\n" +
                "Dengan sistem permainan yang kompetitif, mode Solo, Duo, dan Squad, serta mode Ranked untuk pertandingan peringkat, PUBG terus berkembang sebagai salah satu game battle royale paling populer. Turnamen eSports PUBG juga berkembang pesat dengan berbagai kompetisi internasional seperti PUBG Global Championship (PGC) dan PUBG Mobile Global Championship (PMGC) yang menarik perhatian jutaan pemain dan penonton di seluruh dunia. PUBG terus mendapatkan pembaruan yang meningkatkan kualitas grafis, mekanik gameplay, serta menambahkan fitur-fitur baru agar tetap relevan dan menarik bagi komunitas pemainnya.\n" +
                "\n" +
                "\n"));

        adapter = new GameAdapter(games);
        recyclerView.setAdapter(adapter);
    }
}